# Generated by Django 4.0.2 on 2022-02-23 21:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Дата публикации')),
                ('subject', models.CharField(max_length=256, unique=True, verbose_name='Заголовок публикации')),
                ('content', models.TextField(verbose_name='Текст новости')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'get_latest_by': ['-data'],
            },
        ),
    ]
